Trainer:
  seed: 123
  exp_dir: 'results/1'
  use_ckpt: false
  ckpt_save_num: 2 # 保留最新的 2 个 ckpt
  ckpt_save_interval: 1 # 5 个 epoch 保存一次 ckpt

  max_epochs: 10
  log_every_n_steps: 1 # 每 1 步 step 打印一次指标

Dataset:
  target: dataloader.DataModuleFromConfig
  batch_size: 8
  num_workers: 0
  train:
    _target_: dataset.MyDataset
    data_dir: 'D:\Downloads\medical'
    mode: train
    length: 16
    augment: false
    size: [32, 32]
  val:
    _target_: dataset.MyDataset
    data_dir: 'D:\Downloads\medical'
    mode: val
    length: ${Dataset.train.length}
    augment: false
    size: ${Dataset.train.size}
  test:
    _target_: dataset.MyDataset
    data_dir: 'D:\Downloads\medical'
    mode: test
    length: ${Dataset.train.length}
    augment: false
    size: ${Dataset.train.size}

UNet:
  _target_: UNet.UNet
  im_channels: ${Dataset.train.length}
  down_channels: [32, 64, 128]
  down_sample: [true, true, false]
  num_heads: 4
  num_down_layers: 1
  num_mid_layers: 1
  num_up_layers: 1
  lr: 1e-4