Trainer:
  seed: 123
  exp_dir: './results/0'            # 训练结果保存路径 (ckpt, log (wandb 会保存在根目录), etc.)
  logger: tensorboard                     # wandb / tensorboard / null
  use_ckpt: true
  ckpt_save_num: 1                  # 保留最新的 x 个 ckpt
  ckpt_save_interval: 5             # x 个 epoch 保存一次 ckpt
  max_epochs: 10
  log_every_n_steps: 1              # 每 1 步 step 打印一次训练指标
  check_val_every_n_epoch: 1        # 每 x 个 epoch 验证一次

Dataset:
  target: dataloader.DataModuleFromConfig
  batch_size: 1
  num_workers: 0
  train:
    _target_: dataset.MyDataset
    data_dir: 'D:\Downloads\medical'
    mode: train
    length: 1             # 2D 卷积就把这里设为 1 (目前 3D 卷积还在 dev 阶段)
    augment: false         # 是否使用数据增强
    size: [32, 32]        # 这个参数目前只支持 3D 卷积, 2D 卷积会无视这个参数

    # use_metadata 和 accelerate 是两种不同的加速方式, 只开其中一个为 true 就行
    use_metadata: false    # 是否将数据集路径缓存到本地加速读取
    accelerate: true     # 是否将数据集转换为 npy 到本地加速读取
    
    debug: false          # 是否使用 debug 模式, debug 模式下只会读取 10 个数据
  val:
    _target_: dataset.MyDataset
    data_dir: ${Dataset.train.data_dir}
    mode: val
    length: ${Dataset.train.length}
    augment: ${Dataset.train.augment}
    size: ${Dataset.train.size}
    use_metadata: ${Dataset.train.use_metadata}
    debug: ${Dataset.train.debug}
    accelerate: ${Dataset.train.accelerate}
  test:
    _target_: dataset.MyDataset
    data_dir: ${Dataset.train.data_dir}
    mode: test
    length: ${Dataset.train.length}
    augment: ${Dataset.train.augment}
    size: ${Dataset.train.size}
    use_metadata: ${Dataset.train.use_metadata}
    debug: ${Dataset.train.debug}
    accelerate: ${Dataset.train.accelerate}

UNet:
  _target_: UNet.UNet
  im_channels: ${Dataset.train.length}
  down_channels: [32, 64, 128, 256]
  down_sample: [true, true, true, false]
  num_heads: 4
  num_down_layers: 1
  num_mid_layers: 1
  num_up_layers: 1
  lr: 1e-4